# Site settings 
title: PyMKS Class 
header-img: img/home-bg.jpg 
email: pgriffiths3@gatech.edu 
description: "Taking the struggle bus to avoid the fail train" 
baseurl: "/PyMKS-Class" 
url: "http://pgriffiths3.github.io" 
github_username:  pgriffiths3 
project_repository: PyMKS-Class 
disqus_shortname: project-pages 
# Build settings 
# Don't change these variables 
markdown: kramdown 
highlighter: pygments 
permalink: pretty 
paginate: 5 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] 
